/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./../components/common/BaseButton.vue')['default']
    GlobalAlert: typeof import('./../components/global/GlobalAlert.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    LeftNavigation: typeof import('./../components/common/drawerNav/LeftNavigation.vue')['default']
    LoginButton: typeof import('./../components/common/navigation/LoginButton.vue')['default']
    MessageInfo: typeof import('./../components/global/MessageInfo.vue')['default']
    RegisterButton: typeof import('./../components/common/navigation/RegisterButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../components/common/navigation/SearchBar.vue')['default']
    Snackbar: typeof import('./../components/global/Snackbar.vue')['default']
    ThemeButton: typeof import('./../components/common/navigation/ThemeButton.vue')['default']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    TopNavigation: typeof import('./../components/common/navigation/TopNavigation.vue')['default']
    UserMenu: typeof import('./../components/common/UserMenu.vue')['default']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
  }
}
