/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Combination/': RouteRecordInfo<'/Combination/', '/Combination', Record<never, never>, Record<never, never>>,
    '/Combination/AboutPage': RouteRecordInfo<'/Combination/AboutPage', '/Combination/AboutPage', Record<never, never>, Record<never, never>>,
    '/Combination/HomePage': RouteRecordInfo<'/Combination/HomePage', '/Combination/HomePage', Record<never, never>, Record<never, never>>,
    '/Combination/PostDetailPage': RouteRecordInfo<'/Combination/PostDetailPage', '/Combination/PostDetailPage', Record<never, never>, Record<never, never>>,
    '/Combination/PostListPage': RouteRecordInfo<'/Combination/PostListPage', '/Combination/PostListPage', Record<never, never>, Record<never, never>>,
    '/Combination/ProfilePage': RouteRecordInfo<'/Combination/ProfilePage', '/Combination/ProfilePage', Record<never, never>, Record<never, never>>,
    '/Single/LoginPage': RouteRecordInfo<'/Single/LoginPage', '/Single/LoginPage', Record<never, never>, Record<never, never>>,
    '/Single/NotFoundPage': RouteRecordInfo<'/Single/NotFoundPage', '/Single/NotFoundPage', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/Combination/index.vue': {
      routes: '/Combination/'
      views: never
    }
    'src/pages/Combination/AboutPage.vue': {
      routes: '/Combination/AboutPage'
      views: never
    }
    'src/pages/Combination/HomePage.vue': {
      routes: '/Combination/HomePage'
      views: never
    }
    'src/pages/Combination/PostDetailPage.vue': {
      routes: '/Combination/PostDetailPage'
      views: never
    }
    'src/pages/Combination/PostListPage.vue': {
      routes: '/Combination/PostListPage'
      views: never
    }
    'src/pages/Combination/ProfilePage.vue': {
      routes: '/Combination/ProfilePage'
      views: never
    }
    'src/pages/Single/LoginPage.vue': {
      routes: '/Single/LoginPage'
      views: never
    }
    'src/pages/Single/NotFoundPage.vue': {
      routes: '/Single/NotFoundPage'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
